from PIL import Image
I1 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\随机森林\\acc_litter.jpg')
I2 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\随机森林\\time_litter.jpg')
I3 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\随机森林\\acc_mapping.jpg')
I4 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\随机森林\\time_mapping.jpg')
I5 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\XGB\\acc_litter.jpg')
I6 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\XGB\\time_litter.jpg')
I7 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\XGB\\acc_mapping.jpg')
I8 = Image.open('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\XGB\\time_mapping.jpg')
# I.show()
L1 = I1.convert('L')
L2 = I2.convert('L')
L3 = I3.convert('L')
L4 = I4.convert('L')
L5 = I5.convert('L')
L6 = I6.convert('L')
L7 = I7.convert('L')
L8 = I8.convert('L')

# L.show()
# outfile='C:\\Users\\Administrator\\Desktop\\画图\\数据图\\随机森林\\acc_litter.jpg'
L1.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\1\\acc_litter.jpg')
L2.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\1\\time_litter.jpg')
L3.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\1\\acc_mapping.jpg')
L4.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\1\\time_mapping.jpg')
L5.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\2\\acc_litter.jpg')
L6.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\2\\time_litter.jpg')
L7.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\2\\acc_mapping.jpg')
L8.save('C:\\Users\\Administrator\\Desktop\\画图\\数据图\\2\\time_mapping.jpg')
